# Set ENV["SECRET_KEY_BASE"]
# run
bundle exec rake secret
#set the env variable
export SECRET_KEY_BASE=<KeY GENERATED BY RAKE>

# WKHTMLTOPDF dependency:
# sudo apt-get install libxrender1 libfontconfig

##Criar pastas
# sudo mkdir  /samba_volumes
#
# sudo mkdir /system_reports
#
# sudo mkdir /inspection_files 
#
##add to /etc/fstab  file: 
# sudo nano /etc/fstab
#
## equivalente a pasta e-mail:
#//10.0.0.80/e/E-MAIL  /samba_volumes  cifs uid=administrador,username=usuario,password=usuario,iocharset=utf8,sec=ntlm  0  0
#
##Relatorios a serem baixados pelos inspetores
#//10.0.0.80/c/doc/rodolfo\040010101\GRASI\Relatórios /system_reports  cifs uid=administrador,username=usuario,password=usuario,iocharset=utf8,sec=ntlm  0  0
#
##Upload dos laudos dos inspetores
#//10.0.0.80/e/E-MAIL  /inspection_files  cifs uid=administrador,username=usuario,password=usuario,iocharset=utf8,sec=ntlm  0  0
#
##Montar caminhos
# sudo mount -a
#